<?php

namespace Dynamic\Elements\CountDown\Elements;

use \DateTime;
use \DateTimeZone;
use DNADesign\Elemental\Models\BaseElement;
use SilverStripe\Forms\DropdownField;
use SilverStripe\Forms\FieldList;
use SilverStripe\ORM\FieldType\DBField;
use SilverStripe\View\ArrayData;

/**
 * Class ElementCountDown
 * @package Dynamic\Elements\Elements
 *
 * @property string $End
 * @property string Timezone
 * @property boolean $ShowMonths
 * @property boolean $ShowSeconds
 * @property boolean $Elapse
 */
class ElementCountDown extends BaseElement
{
    /**
     * @var string
     */
    private static $icon = 'font-icon-clock';

    /**
     * @var string
     */
    private static $singular_name = 'Countdown Element';

    /**
     * @var string
     */
    private static $plural_name = 'Countdown Elements';

    /**
     * @var string
     */
    private static $description = 'Displays a countdown to a specific date and time.';

    /**
     * @var array
     */
    private static $db = [
        'End' => 'DBDatetime',
        'Timezone' => 'Varchar(20)',
        'ShowMonths' => 'Boolean',
        'ShowSeconds' => 'Boolean',
        'Elapse' => 'Boolean',
    ];

    /**
     * @var string
     */
    private static $table_name = 'ElementCountDown';

    /**
     * @var ArrayData
     */
    private $client_config;

    /**
     * Sets the Date field to the current date.
     */
    public function populateDefaults()
    {
        $this->End = date('Y-m-d', strtotime("+30 days"));
        parent::populateDefaults();
    }

    /**
     * @return string
     */
    public function getSummary()
    {
        $end = $this->dbObject('End');
        $timezone = $this->dbObject('Timezone');
        return DBField::create_field(
            'HTMLText',
            "Count down to {$end->Date()} {$end->Time()} {$timezone}"
        )->Summary(20);
    }

    public function getCMSFields()
    {
        $this->beforeUpdateCMSFields(function (FieldList $fields) {
            $fields->replaceField(
                'Timezone',
                DropdownField::create('Timezone')
                    ->setSource($this->getTimezoneList())
            );
        });
        return parent::getCMSFields(); // TODO: Change the autogenerated stub
    }

    /**
     * originally from https://davidhancock.co/2013/05/generating-a-list-of-timezones-with-php/
     * @return array
     */
    function getTimezoneList()
    {
        $timezoneIdentifiers = DateTimeZone::listIdentifiers(DateTimeZone::ALL);
        $utcTime = new DateTime('now', new DateTimeZone('UTC'));

        $tempTimezones = [];
        foreach ($timezoneIdentifiers as $timezoneIdentifier) {
            $currentTimezone = new DateTimeZone($timezoneIdentifier);

            $tempTimezones[] = array(
                'offset' => (int)$currentTimezone->getOffset($utcTime),
                'identifier' => $timezoneIdentifier,
            );
        }

        // Sort the array by offset,identifier ascending
        usort($tempTimezones, function ($a, $b) {
            if ($a['offset'] == $b['offset']) {
                return strcmp($a['identifier'], $b['identifier']);
            }
            return $a['offset'] - $b['offset'];
        });

        $timezoneList = [];
        foreach ($tempTimezones as $tz) {
            $sign = ($tz['offset'] > 0) ? '+' : '-';
            $offset = gmdate('H:i', abs($tz['offset']));
            $timezoneList["UTC{$sign}{$offset}"] = "(UTC {$sign}{$offset}) {$tz['identifier']}";
        }

        return $timezoneList;
    }

    /**
     * @return array
     */
    protected function provideBlockSchema()
    {
        $blockSchema = parent::provideBlockSchema();
        $blockSchema['content'] = $this->getSummary();
        return $blockSchema;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return _t(__CLASS__ . '.BlockType', 'Countdown');
    }

    /**
     * @return $this
     */
    public function setClientConfig()
    {
        $clientArray = [
            'End' => "{$this->End}  {$this->Timezone}",
            'Elapse' => $this->Elapse,
        ];

        $this->client_config = ArrayData::create($this->encodeArrayValues($clientArray));

        return $this;
    }

    /**
     * @return ArrayData
     */
    public function getClientConfig()
    {
        if (!$this->client_config) {
            $this->setClientConfig();
        }

        return $this->client_config;
    }

    /**
     * @param $array
     * @return mixed
     */
    protected function encodeArrayValues($array)
    {
        foreach ($array as $key => $val) {
            $array[$key] = json_encode($val);
        }

        return $array;
    }
}
